### ISSUE TITLE
Leaving the room

### ISSUE THREAD

**Issue by Senc3951** [RugbugRedfern/FPS-Game-Tutorial#12]
I implemented a menu and one of the options is a leave button which works using PhotonNetwork.LeaveRoom but it throws an error that there is a duplicate photon id of 999.
(It exists but throws an error, and if I try to join another room, the player manager isn't being instantiated)

**Comment by RugbugRedfern** [comment]
I made a solution to this a while ago: https://gist.github.com/RugbugRedfern/fa76a0a98df6d9d2755bd33c94b9a0e1
