### ISSUE TITLE
Don't check in your PhotonServerSettings

### ISSUE THREAD

**Issue by Tobias-EG** [RugbugRedfern/FPS-Game-Tutorial#3]
You should make sure that you don't check in:
/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

At least not in a shared, public repo. It contains your appid.

**Comment by RugbugRedfern** [comment]
It was not supposed to be pushed but ended up being pushed anyway. Thanks for the heads up, I'll change the Id.
