### ISSUE TITLE
I saw your FPS Game tutorial on YouTube, could you please learn your Redmatch 2 source code

### ISSUE THREAD

**Issue by 2276089666** [RugbugRedfern/FPS-Game-Tutorial#8]

**Comment by RugbugRedfern** [comment]
Not sure what you mean. Do you want me to release the source code of Redmatch 2? Because I can't do that

**Comment by 2276089666** [comment]
Yes, I'm very interested in your redmatch 2. I want to learn the source code of redmatch 2. Thank you

**Comment by RugbugRedfern** [comment]
Sorry, but I can't release the source code of Redmatch 2 because it would make hacking incredibly easy. The FPS series' code was very similar to Redmatch 2's, though, before I stopped using Photon.

**Comment by 2276089666** [comment]
Ha ha, hateful hacker, please update the tutorial on your YouTube
